# Generated by Django 4.1 on 2022-09-20 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0002_competencia_lugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencia',
            name='nombreCompe',
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='nombreLugar',
        ),
    ]
