# Generated by Django 4.1 on 2022-09-20 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0003_remove_competencia_nombrecompe_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Competencia',
        ),
        migrations.DeleteModel(
            name='Lugar',
        ),
    ]
