# Generated by Django 4.1 on 2022-09-20 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0005_competencia_lugar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lugar',
        ),
    ]
